extends:
  - '@cisco-developer/api-insights-openapi-rulesets/api-insights-openapi-ruleset.js'
  - '@cisco-developer/api-insights-openapi-rulesets/contract.js'
  - '@cisco-developer/api-insights-openapi-rulesets/documentation.js'
