name: Spectral Lint
permissions: 
  pull-requests: write
  actions: write
  statuses: write
on:
  pull_request:
    branches:
      - main # or master, or whatever branch you target with PRs

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20' # or your preferred Node version

      - name: Install dependencies
        run: yarn install

      - name: Generate OpenAPI spec
        run: yarn generate

      # Run Spectral
      - uses: stoplightio/spectral-action@latest

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file_glob: 'spec/*.json'
