name: Spectral Lint
permissions: write-all
on:
  pull_request:
    branches:
      - main # or master, or whatever branch you target with PRs
  release:
    types:
      - created
jobs:
  lint:
    runs-on: ubuntu-latest
    environment:
      name: GithubActions

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20' # or your preferred Node version

      - name: Install dependencies
        run: yarn install

      - name: Generate OpenAPI spec
        run: yarn generate

      # Run Spectral
      - uses: stoplightio/spectral-action@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file_glob: 'spec/*.json'

      # Extra step that runs only on release
      - name: Update Documentation
        run: yarn updatePostman
        env:
          POSTMAN_API_KEY: ${{ secrets.POSTMAN_API_KEY }}
        if: github.event_name == 'release'
